### ISSUE TITLE
SFTP beanstalk / filezilla bugs

### ISSUE THREAD

**Issue by krodyrobi** [PressLabs/gitfs#232] opened 2016-05-16 15:41 UTC
This is super urgent

**Comment by vtemian** [comment] 2016-05-16 15:46
Related / duplicate of: https://github.com/PressLabs/gitfs/issues/231  https://github.com/PressLabs/gitfs/issues/231

**Comment by calind** [comment] 2016-05-20 11:56
Duplicate of #223.

**Closed** 2016-05-20 11:57 UTC
Labels: bug
